USE `xpto`;

CREATE TABLE IF NOT EXISTS `empresa` (

    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CNPJ VARCHAR( 14 ) NOT NULL UNIQUE,
    RAZAO_SOCIAL VARCHAR( 255 ) NOT NULL,
    NOME_FANTASIA VARCHAR( 255 ) NOT NULL

) ENGINE=InnoDB DEFAULT CHARSET=utf8;
